name: "Example 1: Basic usage"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
  schedule:
    # Note that cronjobs run on master/main by default
    - cron: "0 0 * * *"

jobs:
  example-1:
    # prevent cronjobs from running on forks
    if:
      (github.event_name == 'schedule' && github.repository ==
      'conda-incubator/setup-miniconda') || (github.event_name != 'schedule')
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest"]
        python-version: ["3.7"] #, "2.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./
        with:
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Environment
        shell: bash -l {0}
        run: printenv | sort
